[workspace]
members = [
	"pallets/hello-substrate",
	"runtimes/minimal-grandpa-runtime",
	"runtimes/super-runtime",
	"nodes/basic-pow",
	"nodes/hybrid-consensus",
	"consensus/sha3pow",
	"traits/account-set",
]
